### ISSUE TITLE
setGame, every so often the Bot removes it's "Playing" tag

### ISSUE THREAD

**Issue by Forbidden-Duck** [WeebDev/Commando#67]
When using
`if (message.author.id === '190775609532612608') { if (!argresult) argresult = null; if (message.content.startsWith(prefix + 'setgame')) { this.client.user.setGame(argresult) } } else { message.channel.sendMessage(${message.author}, You do not have Administrative permission to use that command) }`

Code in Discord-Commando. The bot enables it's "Playing " tag correctly. After a few minutes it deletes that tag for no reason.

**Comment by vzwGrey** [comment]
This is the repository for the Commando bot, not the framework itself.
Please ask your discord.js-commando related questions on the [Offical Discord.js server](https://discord.gg/bRCvFy9) in the `#support-commando` channel.
