### ISSUE TITLE
TypeError: Cannot read property 'get' of null

### ISSUE THREAD

**Issue by Jwiggiff** [WeebDev/Commando#68]
It's all in the title. how do I fix this??

**Comment by alucard0134** [comment]
You're providing little to no context to how this issue occurred...

**Comment by Jwiggiff** [comment]
how can I provide more? I don't know anything else

**Comment by alucard0134** [comment]
jesus christ

what happened to cause that error?

did you even start the app?

**Comment by Jwiggiff** [comment]
oh, I feel dumb.

I ran the play command. it said
`@C:\Users\Dev, obtaining video details...
@C:\Users\Dev, An error occurred while running the command: TypeError: Cannot read property 'get' of null
You shouldn't ever receive an error like this.
Please contact jcool.friedman#9208.`

**Comment by alucard0134** [comment]
can you goto the terminal you started the app with and paste the stack trace?

**Comment by ShayBox** [comment]
Yea, i just got this. probably a simple solution but i've never messed with this stuff :/

**Comment by ShayBox** [comment]
And thats all there is, no line, no console error. so i can't provide more.

**Comment by ShayBox** [comment]
Figured it out, its from line 114. cant get volume or cant get msg.guild.id

**Comment by ShayBox** [comment]
Problem is on line 144 of play.js, and all lines with the .get similar to that.
