### ISSUE TITLE
Skipping two songs?

### ISSUE THREAD

**Issue by ShayBox** [WeebDev/Commando#71]
I've found a very weird issue where the bot skips two songs when anyone does !skip and there's 3 or less people, making the skip instant.

**Comment by ShayBox** [comment]
Current version of my code is on https://github.com/ShayBox/ShayBot

**Comment by itskiru** [comment]
uh what? Your are not using docker so idk how he found the youtube_api etc... And btw, use args for your commands.

**Comment by ShayBox** [comment]
I'm new to commando, but i figured out what api to use, and i moved the non secret stuff from the environment variables to the play file, to make it easier, and some other stuff i didn't need like a command for max length and max songs, volume etc. but i haven't messed with the skip command, but it skips two songs in a row when doing it. I'm using heroku and git pushing system, I like it

**Comment by ShayBox** [comment]
Also docker sucks imo, and my commands don't need args, thats the point of using commando

**Comment by itskiru** [comment]
You just don't know how to use docker, and commands need args.

**Comment by iCrawl** [comment]
Doesn't happen to me, also I don't use Heroku to deploy because its like the worst for bots.

**Comment by ShayBox** [comment]
wontfix, but will fix. your issue, also what command needs args, "skip" does not require args, it skips currently playing song, not current and next.

heroku is fine for bots, literally just fine unless you need to use sql or json databases, which is bad, use mysql or mon or some remote database... and for free, its the best option ngl.

**Comment by KyeNormanGill** [comment]
I had this, but it wasn't on commando. I simply added a settimeout for playing the next song and it didn't skip 2 songs.
